#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <vector>
#include <algorithm>
#include <assert.h>
#include <utility>
#include <omp.h>
#include <string>
#include <cstring>
#include <ctime>
#include <map>
